### PR TITLE
Update to vite 4

### PR DESCRIPTION
**Pull request by SiebeVE**

### CODE REVIEW

**Comment by SiebeVE** [comment]
@lhapaipai What do you think about updating to vite 4?

**Comment by lhapaipai** [comment]
hi @SiebeVE ,yes it s a very good idea but i want to test compatibility with vite plugin legacy before merging your pr. i will do this next week.

**Comment by lhapaipai** [comment]
thanks @SiebeVE

**Comment by lhapaipai** [comment]
unfortunatly I went too fast. for the moment vite-bundle is not compatible with vite 4.
2 issues 
- when entry point is a css file (solved in #13 )
- with assets resolutions (didn't have time to solve this evening).

the development dependency for the vite-plugin-symfony may be left but your project must still be on vite 3

**Pull request merged**
